### ISSUE TITLE
时钟小组件未与通知左对齐

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/dde-widgets#15]
## 问题
![image](https://user-images.githubusercontent.com/20967670/220584106-14168474-bda1-47ac-86bf-8e09e04c96d1.png)

## 期望
小组件与通知左对齐
![image](https://user-images.githubusercontent.com/20967670/220584174-a4964708-dab9-4d35-80c8-11ed71aa3ebf.png)

## 建议
通知小组件内部设置了左边距导致

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/dde-widgets/pull/32 对应的可供测试的 deb 包： [dde-widgets_6.0.8_amd64.zip](https://github.com/linuxdeepin/dde-widgets/files/10917541/dde-widgets_6.0.8_amd64.zip)

**Comment by xuqi27837288** [comment]
测试通过

**Comment by BLumia** [comment]
在 https://github.com/linuxdeepin/dde-widgets/pull/58 中解决。
