### ISSUE TITLE
背景与文字样式不对

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/dde-widgets#17]
## 现状
![image](https://user-images.githubusercontent.com/20967670/220586620-125a6692-2826-45be-bd39-a4ee452cce67.png)

## 期望
- 背景增加模糊效果与描边
- 绿色与黄色圆点与文字之间增加间距
- 字体样式颜色加深增加可读性

## 建议
无设计图，效果与设计沟通即可

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/dde-widgets/pull/33 对应的测试包：[dde-widgets_6.0.8_amd64.zip](https://github.com/linuxdeepin/dde-widgets/files/10918925/dde-widgets_6.0.8_amd64.zip)

**Comment by xuqi27837288** [comment]
测试通过
