### ISSUE TITLE
圆角锯齿很严重

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/dde-widgets#18]
## 现状
![image](https://user-images.githubusercontent.com/20967670/220587153-3c6b37f9-ef6f-44fa-9862-e70a84e23a0b.png)

## 期望
调整圆角无锯齿

## 建议
- 需要改动现有圆角的实现方案。
  小组件框架用setMask覆盖了插件提供的widget四角形成的圆角，此方案无法从原理上避免圆角有锯齿
- 尽量让插件不处理这个圆角信息，若有必要，提供一个处理后的qwidget接口。

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
