### ISSUE TITLE
小组件标题字体样式错误

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/dde-widgets#20]
## 现状

![image](https://user-images.githubusercontent.com/20967670/220590642-c06ae16a-ff95-48e6-9550-73610208e7cb.png)

## 期望
字体能够看清

## 建议
是否与背景透明有关，字体可再看设计图

**Comment by ComixHe** [comment]
绘制颜色为预期颜色，但该颜色和背景色的对比度太小

**Comment by BLumia** [comment]
恐怕都要和设计核对一下。和 https://github.com/linuxdeepin/dde-widgets/pull/33 有一些相关性。原始设计里，背景应该是有个渐变模糊的。

**Comment by ComixHe** [comment]
设计预期效果是背景的渐变模糊，但目前没有很好的渐变模糊方案，需要合成器支持，开启全局模糊避免这个问题，已有pr https://github.com/linuxdeepin/dde-widgets/pull/29

**Comment by BLumia** [comment]
PR 合入/问题得到确切解决之前，这个 issue 是不是不应该关闭？

**Comment by ComixHe** [comment]
已合入
