### ISSUE TITLE
屏幕1.25缩放下，小组件内容未居中显示

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/dde-widgets#22]
## 现状
  ![image](https://user-images.githubusercontent.com/20967670/220592894-fefe85de-d97d-45e2-8528-ebea83e1a469.png)

## 期望
从两个方面查看
- 这两个小组件是自己绘制的，缩放后，是否位置计算错误
- 是否是小组件框架错误，未居中显示内容

**Comment by luodeepin** [comment]
验证通过
![image](https://github.com/linuxdeepin/dde-widgets/assets/96416089/0c58b366-b072-4eb8-8713-f69fec2f6ff3)

**Comment by FeiWang1119** [comment]
https://github.com/deepin-community/Repository-Integration/pull/194

**Comment by xuqi27837288** [comment]
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-194/testing/ ./

回归通过
![image](https://github.com/linuxdeepin/dde-widgets/assets/62528742/35ea1613-f0dd-4c80-bc40-24dceee30dc8)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：


![截图_选择区域_20230706112629](https://github.com/linuxdeepin/dde-widgets/assets/62528742/082d05cd-0bb8-4669-9811-9fe930d94940)
