### ISSUE TITLE
介绍信息样式问题

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/dde-widgets#25]
## 现状
- 背景模糊值太高，不够通透
- 标题、版本、开发者、文字介绍这些信息字体样式等
![image](https://user-images.githubusercontent.com/20967670/220594918-7555dd75-3142-4136-a574-74e458d4c5d6.png)

## 期望
![image](https://user-images.githubusercontent.com/20967670/220594951-053657e1-357b-469d-80f0-ddbb1fb11fe7.png)

**Comment by tsic404** [comment]
[dde-widgets_6.0.8_amd64.zip](https://github.com/linuxdeepin/dde-widgets/files/10916906/dde-widgets_6.0.8_amd64.zip)

**Comment by xuqi27837288** [comment]
测试通过
