### ISSUE TITLE
通知中心的部分字体大小没有跟随

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/dde-widgets#5]
[pms](https://pms.uniontech.com/bug-view-160485.html)
[环境]

1、镜像地址：[https://cdimage.uniontech.com/daily-iso/image-snipe/old/CUSTOM/chendan/20220920/ ](https://cdimage.uniontech.com/daily-iso/image-snipe/old/CUSTOM/chendan/20220920/%C2%A0)

2.仓库地址：
deb [trusted=yes] [https://ci.uniontech.com/sniperepo/snipe/snipe-release/ unstable main](https://ci.uniontech.com/sniperepo/snipe/snipe-release/%C2%A0unstable%C2%A0main)
deb [https://pools.uniontech.com/desktop-professional-snipe/ snipe main community commercial](https://pools.uniontech.com/desktop-professional-snipe/%C2%A0snipe%C2%A0main%C2%A0community%C2%A0commercial)
deb [trusted=yes] [https://ci.uniontech.com/sniperepo/snipe/snipe-develop/ develop main](https://ci.uniontech.com/sniperepo/snipe/snipe-develop/%C2%A0develop%C2%A0main)
3、应用版本：dde-control-cenetr:6.0.3+u037

[前置条件]

[步骤]

1.打开控制中心-个性化-字体，设置字号为20

2.查看通知中心的字体大小是否发生变化

[结果]

通知中心的字体大小不发生变化

[期望]

通知中心的字体大小发生变化

[问题]
![image](https://user-images.githubusercontent.com/20967670/219580616-d25921d7-b4cd-4d60-90a0-6d20fa2676a9.png)

**Comment by FeiWang1119** [comment]
https://github.com/deepin-community/Repository-Integration/pull/195

**Comment by xuqi27837288** [comment]
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-195/testing/ ./

测试通过

![image](https://github.com/linuxdeepin/dde-widgets/assets/62528742/03109ab1-a04e-4378-8141-3519788f5c81)

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
【截图录屏】：



![截图_选择区域_20230706112332](https://github.com/linuxdeepin/dde-widgets/assets/62528742/be182260-7864-440c-aacf-8c1d5ce03bc8)
